print("I shall be telling this with a sigh")
print("Somewhere ages and ages hence:")
print("Two reads diverged in a wood, and I--")
print("I took the one less traveled by,")
print("And that has made all the difference.")